# Generated by Django 5.2.8 on 2026-02-03 08:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_careers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterField(
            model_name='careers',
            name='field',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cgpa',
            field=models.FloatField(blank=True, help_text='CGPA should be between 0 and 10', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddIndex(
            model_name='careers',
            index=models.Index(fields=['name'], name='api_careers_name_d1db9d_idx'),
        ),
        migrations.AddIndex(
            model_name='careers',
            index=models.Index(fields=['field'], name='api_careers_field_678c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='api_userpro_user_id_ea9cd5_idx'),
        ),
    ]
